# Generated by Django 3.1 on 2020-08-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fingerprint',
            field=models.CharField(default='XXX', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
