# Generated by Django 3.1 on 2020-08-31 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_post_fingerprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('required', models.BooleanField(default=True)),
                ('value', models.CharField(max_length=2000)),
            ],
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='Item',
        ),
        migrations.DeleteModel(
            name='PostField',
        ),
        migrations.AddField(
            model_name='itemfield',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.item'),
        ),
    ]
