# Generated by Django 3.1 on 2020-10-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_remove_feed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
