# Generated by Django 3.1 on 2020-10-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_auto_20201024_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='rss_link',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
